config/routes.rb
Rails.application.routes.draw do
  resources :maneys
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  resources :salaries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/maney.rb
class Maney < ApplicationRecord
  belongs_to :user
  belongs_to :category

  scope :year_sort_list, -> {
    {
      "並び替え" => "",
      "2022年" => "2022",
      "2023年" => "2023",
    }
  }
  
  scope :month_sort_list, -> {
    {
      "並び替え" => "",
      "1月" => "01",
      "2月" => "02",
      "3月" => "03",
      "4月" => "04",
      "5月" => "05",
      "6月" => "06",
      "7月" => "07",
      "8月" => "08",
      "9月" => "09",
      "10月" => "10",
      "11月" => "11",
      "12月" => "12",
    }
  }
end

app/controllers/maneys_controller.rb
class ManeysController < ApplicationController
  before_action :authenticate_user!
  before_action :set_maney, only: %i[ show edit update destroy ]

  # GET /maneys or /maneys.json
  def index
    if sort_params.present?
      @year = sort_params[:year]
      @month = sort_params[:month]
      date = Date.parse(@year + "/" + @month)
      @maneys = current_user.maneys.where(created_at: date.all_month).order("created_at asc")
      @chart = current_user.maneys.where(created_at: date.all_month)
    else
      #今月
      @maneys = current_user.maneys.where(created_at: Time.current.all_month).order("created_at asc")
      @chart = current_user.maneys.where(created_at: Time.current.all_month)
    end
    @year_sort_list = Maney.year_sort_list
    @month_sort_list = Maney.month_sort_list
    @categories = Category.all
    #月々使えるお金を算出する
    @salaries = Salary.where(user_id: current_user.id)
    @annual_income = @salaries.pluck(:annual_income)[0]
    @bonus = @salaries.pluck(:bonus)[0]
    @rent = @salaries.pluck(:rent)[0]
    @salary = (@annual_income - @bonus) / 12 - @rent
  end

  # GET /maneys/1 or /maneys/1.json
  def show
  end

  # GET /maneys/new
  def new
    @maney = current_user.maneys.new
    @categories = Category.all
  end

  # GET /maneys/1/edit
  def edit
    @categories = Category.all
  end

  # POST /maneys or /maneys.json
  def create
    @maney = current_user.maneys.new(maney_params)

    respond_to do |format|
      if @maney.save
        format.html { redirect_to maneys_path, notice: "Maney was successfully created." }
        format.json { render :show, status: :created, location: @maney }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @maney.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maneys/1 or /maneys/1.json
  def update
    respond_to do |format|
      if @maney.update(maney_params)
        format.html { redirect_to maneys_path, notice: "Maney was successfully updated." }
        format.json { render :show, status: :ok, location: @maney }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @maney.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maneys/1 or /maneys/1.json
  def destroy
    @maney.destroy

    respond_to do |format|
      format.html { redirect_to maneys_url, notice: "Maney was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maney
      @maney = current_user.maneys.find(params[:id])
      redirect_to(maneys_url, alert: "ERROR!!") if @maney.blank?
    end

    # Only allow a list of trusted parameters through.
    def maney_params
      params.require(:maney).permit(:content, :price, :integer, :user_id, :category_id)
    end

    def sort_params
      params.permit(:year, :month)
    end 
end

app/helpers/maneys_helper.rb
module ManeysHelper
end

app/views/maneys/_form.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_with(model: @maney, remote: true) do |form| %>
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">お金の登録</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <% if @maney.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(maney.errors.count, "error") %> prohibited this maney from being saved:</h2>

              <ul>
                <% maney.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= form.label :content, class: "col-sm-2 col-form-label" %>
            <div>
              <%= form.text_field :content, class: "form-control" %>
            </div>
          </div>

          <div class="form-group">
            <%= form.label :price, class: "col-sm-2 col-form-label" %>
            <%= form.text_field :price, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= form.label :category, "カテゴリー", class: "col-sm-2 col-form-label" %>
            <%= form.collection_select(:category_id, @categories, :id, :name, prompt: "選択してください") %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type='submit' class="btn btn-primary">登録する</button>
        </div>
      <% end %>
    </div>
  </div>

app/views/maneys/_maney.html.erb
<tr id="maney-<%= maney.id %>">
  <td><%= maney.content %></td>
  <td><%= maney.price %></td>
  <td><%= maney.category.name %></td>
  <td>
    <div class="btn-group">
      <button type="button" class="btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v align-middle"></i>
      </button>
      <div class="dropdown-menu dropdown-menu-right text-middle">
        <%= link_to "編集", edit_maney_path(maney), class: "dropdown-item", remote: true %>
        <%= link_to "削除", maney_path(maney), method: :delete, class: "dropdown-item text-danger", data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  </td>
</tr>

app/views/maneys/create.js.erb
$("tbody").prepend("<%= j(render @maney) %>");
$("#savings-modal").modal("hide");

app/views/maneys/edit.js.erb
$("#savings-modal").html("<%= escape_javascript(render 'form') %>");
$("#savings-modal").modal("show");

app/views/maneys/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mt-3 mb-3"><%= current_user.name%>さんの家計簿</h1>

<div>
  <h3>月々に使えるお金</h3>
  <span class="font-weight-bold"><%= @salary %>万円(家賃込み)</span>
</div>

<div class="mt-3 mb-3">
  <%= link_to new_maney_path, class: "btn p-0 text-dark",remote: true do %>
    <i class="fas fa-plus align-middle pr-1"></i><span class="align-middle">お金を登録する</span>
  <% end %>
</div>

<div id="savings-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<div class="text-center">
  <h3>今月の支出額</h3>
  <%= @chart.all.sum(:price) %>
</div>

<div class="mt-3 mb-3" style="margin-left:29%;">
  <%= pie_chart @chart.joins(:category).group("categories.name").sum(:price) %>
</div>

<div class="mt-3 mb-3"> 
  <%= form_with url: maneys_path, method: :get do |f| %>
    <% if @year.present? %>
      <%= f.select :year, @year_sort_list, selected: @year %>
      <%= f.select :month, @month_sort_list, selected: @month %>
    <% else %>
      <%= f.select :year, @year_sort_list %>
      <%= f.select :month, @month_sort_list %>
    <% end %>
    <%= f.button "表示", onClick: "javascript: this.form.submit();" %>
  <% end %>
</div>

<table class="table mt-3">
  <thead>
    <tr>
      <th scope="col">Content</th>
      <th scope="col">Price</th>
      <th scope="col">Category</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <%= render @maneys %>
  </tbody>
</table>

app/views/maneys/new.js.erb
$("#savings-modal").html("<%= escape_javascript(render 'form') %>");
$("#savings-modal").modal("show");

app/views/maneys/update.js.erb
$("#maney-<%= @maney.id %>").html('<%= j(render @maney) %>');
$("#savings-modal").modal("hide");